sudo: required  # https://docs.travis-ci.com/user/ci-environment/
language: python3

install:
  - python pip install --user requirements.txt
  - pip install coveralls
script: make ci
after_success: coveralls

notifications:
  email:
    on_success: never
    on_failure: change
